In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [6]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [9]:
x @ np.ones(3)

array([ 6., 15.])

In [10]:
from numpy.linalg import inv, qr

In [11]:
X = np.random.randn(5, 5)

In [12]:
mat = X.dot(X)

In [15]:
# 역행렬
inv(mat)

array([[ 2037.89854703, -7993.79198919,   258.62373458,  -809.74812026,
         -301.11840243],
       [ -234.28202974,   919.35597786,   -29.62159522,    93.15260524,
           34.78759431],
       [  627.19669186, -2461.20102157,    79.95365918,  -248.95959991,
          -92.64369901],
       [-1938.25467572,  7596.05006829,  -247.21448727,   769.13543004,
          287.02859293],
       [-2119.48544215,  8304.07311268,  -269.42482453,   839.8739771 ,
          314.11277055]])

In [16]:
# 전치행렬
mat.dot(inv(mat))

array([[ 1.00000000e+00, -4.26607169e-13,  3.74694011e-14,
        -4.00841475e-14,  2.63720666e-14],
       [ 4.32377003e-14,  1.00000000e+00,  1.17897614e-14,
        -1.61434719e-14,  3.33311298e-15],
       [-1.94974806e-14,  7.10256506e-13,  1.00000000e+00,
         6.30938293e-14, -1.51332295e-14],
       [-3.08231972e-13,  1.13550145e-12, -7.50354593e-15,
         1.00000000e+00, -7.13235657e-14],
       [ 2.77451502e-13, -1.74514210e-12,  3.65315801e-14,
        -1.24754637e-13,  1.00000000e+00]])

In [17]:
# QR factorization
q, r = qr(mat)

In [18]:
r

array([[-1.16571378e+00, -4.41424413e+00,  1.29983363e+00,
        -4.41527884e-01,  1.55675111e-01],
       [ 0.00000000e+00,  3.05492435e+00,  9.43262822e-01,
         9.97770685e-02, -1.49915031e-01],
       [ 0.00000000e+00,  0.00000000e+00,  1.11926675e+00,
         4.92713073e-01, -1.19000747e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -7.67433665e-01,  7.01997963e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.15992037e-04]])

In [20]:
q

array([[-0.33462811,  0.24680103, -0.78266242, -0.39257333, -0.24584343],
       [-0.07055551,  0.00976898, -0.25820546, -0.02213445,  0.96320636],
       [ 0.41150777,  0.65007584, -0.25458191,  0.58504203, -0.03125113],
       [ 0.28287286,  0.57217214,  0.36524783, -0.67060093,  0.09741869],
       [-0.79604664,  0.43475771,  0.35007363,  0.23112002,  0.03643458]])