In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[0.97653353, 0.01149741, 0.94031339],
       [1.09796137, 1.41996527, 0.16206173]])

In [4]:
data * 10

array([[ 9.76533533,  0.11497408,  9.40313387],
       [10.97961367, 14.19965269,  1.6206173 ]])

In [5]:
data + data

array([[1.95306707, 0.02299482, 1.88062677],
       [2.19592273, 2.83993054, 0.32412346]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### ndarray 생성

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int64')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros([3, 6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
# 초기화되지 않은 배열 반환
np.empty((2,3,2))

array([[[1.1551239e-316, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray의 자료형

In [22]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [23]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [24]:
arr1

array([1., 2., 3.])

In [25]:
arr2

array([1, 2, 3], dtype=int32)

In [26]:
arr = np.array([1,2,3,4,5])

In [27]:
arr.dtype

dtype('int64')

In [28]:
float_arr = arr.astype(np.float64)

In [29]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [30]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [32]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [33]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
int_array = np.arange(10)

In [36]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [37]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
empty_uint32 = np.empty(8, dtype='u4')

In [39]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### 배열과 스칼라 간의 연산

In [40]:
arr =np.array([[1., 2., 3.], [4., 5., 6.]])

In [41]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [42]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [44]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 색인과 슬라이싱

In [45]:
arr = np.arange(10)

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [48]:
arr_slice = arr[5:8]

In [49]:
arr_slice[1] =  12345

In [50]:
arr_slice[:] = 64

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [53]:
arr2d[2]

array([7, 8, 9])

In [54]:
arr2d[0,2]

3

In [55]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [56]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
old_values = arr3d[0].copy()

In [59]:
arr3d[0] = 42

In [60]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0] = old_values

In [62]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### 슬라이스 색인

In [63]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [64]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [67]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### 불리언 색인

In [68]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [69]:
data = np.random.randn(7,4)

In [70]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [71]:
data

array([[-0.6945171 , -0.405549  ,  1.70234239, -1.46659274],
       [-1.81480842, -0.16280865,  0.57117515, -1.16918523],
       [ 1.44238379, -0.12371218,  0.18458504, -1.66857844],
       [-0.03457357, -0.54075692,  0.19562543,  0.74064062],
       [-1.25796923,  0.86010848,  0.20149304,  1.51136262],
       [ 1.44687897, -0.77357395, -0.73903746,  0.1401294 ],
       [ 0.59417178,  1.52345654,  0.47158303, -0.251407  ]])

In [72]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [73]:
data[names == 'Bob']

array([[-0.6945171 , -0.405549  ,  1.70234239, -1.46659274],
       [-0.03457357, -0.54075692,  0.19562543,  0.74064062]])

In [74]:
data[names == 'Bob', 2:]

array([[ 1.70234239, -1.46659274],
       [ 0.19562543,  0.74064062]])

In [75]:
data[names == 'Bob', 3]

array([-1.46659274,  0.74064062])

In [76]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [77]:
data[~(names == 'Bob')]

array([[-1.81480842, -0.16280865,  0.57117515, -1.16918523],
       [ 1.44238379, -0.12371218,  0.18458504, -1.66857844],
       [-1.25796923,  0.86010848,  0.20149304,  1.51136262],
       [ 1.44687897, -0.77357395, -0.73903746,  0.1401294 ],
       [ 0.59417178,  1.52345654,  0.47158303, -0.251407  ]])

### 팬시 색인

In [78]:
arr = np.empty((8, 4))

In [79]:
for i in range(8):
    arr[i] = i

In [80]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [81]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [82]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [83]:
arr =np.arange(32).reshape((8,4))

In [84]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [85]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [86]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [87]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 배열 전치와 축 바꾸기

In [94]:
arr = np.arange(15).reshape((3, 5))

In [95]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [100]:
arr = np.random.randn(6, 3)

In [105]:
arr

array([[-0.82839521, -0.242733  , -0.61916133],
       [ 0.38897403,  0.79586217,  1.41239617],
       [ 0.26176192, -1.19597171,  0.24956211],
       [ 0.53299309, -0.57127865,  0.41615679],
       [ 0.00164403, -0.26613919,  1.55456928],
       [-0.65290379,  1.26030215,  0.01695317]])

In [106]:
np.dot(arr.T, arr)

array([[ 1.61642642, -0.93019245,  1.34091724],
       [-0.93019245,  4.10821512,  0.34578716],
       [ 1.34091724,  0.34578716,  5.03066446]])

In [107]:
arr.T

array([[-0.82839521,  0.38897403,  0.26176192,  0.53299309,  0.00164403,
        -0.65290379],
       [-0.242733  ,  0.79586217, -1.19597171, -0.57127865, -0.26613919,
         1.26030215],
       [-0.61916133,  1.41239617,  0.24956211,  0.41615679,  1.55456928,
         0.01695317]])

In [108]:
arr = np.arange(16).reshape((2, 2, 4))

In [109]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [110]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [113]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])