In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
nwalks = 5000
nsteps = 1000

In [5]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)

In [6]:
walks = steps.cumsum(1)

In [7]:
walks

array([[ -1,  -2,  -3, ..., -22, -23, -22],
       [ -1,  -2,  -1, ..., -16, -15, -16],
       [  1,   0,  -1, ..., -46, -47, -46],
       ...,
       [  1,   2,   1, ..., -32, -31, -30],
       [  1,   2,   3, ..., -10,  -9,  -8],
       [ -1,  -2,  -3, ..., -18, -19, -20]])

In [9]:
walks.max()

116

In [10]:
walks.min()

-113

In [13]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

array([ True, False,  True, ...,  True,  True, False])

In [14]:
hits30.sum()

3429

In [19]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

505.56167979002623

In [21]:
steps = np.random.normal(loc=0, scale=0.25, size=(nwalks, nsteps))
steps

array([[-0.04332621, -0.08292818,  0.10209837, ..., -0.17077027,
         0.02636326, -0.21097658],
       [ 0.21006876,  0.34260862, -0.35975254, ..., -0.0092429 ,
         0.03830943, -0.29676171],
       [ 0.30982137,  0.10637072, -0.19852827, ..., -0.0330987 ,
        -0.19543805, -0.13869204],
       ...,
       [-0.07667086, -0.26117446, -0.24178319, ...,  0.29146274,
         0.04826704,  0.52771052],
       [-0.31460924,  0.17440333,  0.07910321, ..., -0.43777408,
         0.22467989, -0.11410971],
       [ 0.02031775,  0.0682308 , -0.17666454, ...,  0.12276164,
         0.00515645,  0.31570833]])