In [23]:
import numpy as np

In [24]:
arr = np.arange(10)

In [25]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [26]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [27]:
x = np.random.randn(8)

In [28]:
y = np.random.randn(8)

In [29]:
x

array([-0.11654153, -0.2944312 , -1.1703212 , -0.60480878, -0.72087247,
       -1.05270884,  1.36107859, -0.37207437])

In [30]:
y

array([ 2.07260347, -0.42956891, -1.44663019,  0.56699977,  1.32332948,
        0.24077839, -1.53237667, -0.23063553])

In [31]:
# 이항 유니버설 함수
np.maximum(x, y)

array([ 2.07260347, -0.2944312 , -1.1703212 ,  0.56699977,  1.32332948,
        0.24077839,  1.36107859, -0.23063553])

In [33]:
arr = np.random.randn(7) * 5

In [35]:
arr

array([-2.60975639,  1.16713673,  8.35277883, -2.24694673, -2.38202121,
        7.53185607, -2.24895582])

In [34]:
np.modf(arr)

(array([-0.60975639,  0.16713673,  0.35277883, -0.24694673, -0.38202121,
         0.53185607, -0.24895582]), array([-2.,  1.,  8., -2., -2.,  7., -2.]))